name: upload exe

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/Prince-of-sea/pyinstaller-builder/releases/download/snapshot/pyinstaller-6.11.1-py3-none-any.whl
          pip install -r requirements.txt
          
      - name: Run Python - create_licenses_txt
        run: python '.github/workflows/create_licenses_txt.py'

      - name: Build EXE
        run: >
          pyinstaller src/_main.py --hidden-import=_cffi_backend
          --add-data 'src/__icon.ico;./'
          --add-data 'src/lang/ui.ja.yml;./lang/'
          --add-data 'src/lang/var.ja.yml;./lang/'
          --add-data 'src/lang/ui.zh.yml;./lang/'
          --add-data 'src/lang/var.zh.yml;./lang/'
          --add-data 'src/lang/ui.en.yml;./lang/'
          --add-data 'src/lang/var.en.yml;./lang/'
          --add-data 'licenses_py.txt;./'
          --onefile --icon src/__icon.ico --name ONScripter_Multi_Converter.exe

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@6034af24fba4e5a8e975aaa6056554efe4c794d0
        with:
          fail_on_unmatched_files: true
          files: |
            **/ONScripter_Multi_Converter.exe
